# *****************************************************
# Variables to control Makefile operation
#Compiler of choice 
CC = g++
CFLAGS = -Wall
CFLAGS += -g
CFLAGS += -fPIC
# ****************************************************
# Targets needed to bring the executable up to date

#	doPrint: doPrint.cpp 
#		$(CC) $(CFLAGS) doPrint.cpp -o doPrint.o
