name: Verible linter example
on:
  pull_request_target: master

jobs:
   lint:
      runs-on: ubuntu-latest
   
   permissions:
      checks: write
      contents: read
      pull-requests: write
   steps:
      - uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.head.sha }}
        
        exclude_paths: |
            ./*
